server {
    listen 80;
    listen [::]:80;
    server_name guitar-pro-converter.eva-chat.ru;
    root /var/www/guitar-pro-converter/current;
    location ^~ /.well-known/acme-challenge/ { root /var/www/guitar-pro-converter/acme; }
    location / { try_files $uri $uri/ =404; }
    add_header X-Content-Type-Options nosniff always;
    add_header Referrer-Policy no-referrer always;
}
